### ISSUE TITLE
[PLAN] Provide PowerPC .NET Port

### ISSUE THREAD

**Issue by abebeos** [abebeos/runtimelab-ppc#4]
(draft)

## Main Project

https://github.com/abebeos/runtimelab-ppc

(upstreams: https://github.com/dotnet/runtimelab, https://github.com/dotnet/runtime)

## Summary

The overall plan is to align the work with the s390x port, setup a simplified collaborative dev environment independent of MS/IBM, isolate-document tasks on subsystems so 3rd-parties can fulfill them in parallel, move projects over to official repos when the time comes (maturity).

## Deadline

* ideally, this gets into .NET 6 release (Nov. 2021)

## Requirements

* must support `ppc64le`
* should support `ppc64`

## Project Stages

*    Each stage is a result in itself (e.g. is beneficial to other devs continuing the work).
*    Each stage is usually negotiated separately (one or more bounties).

## Stage 1: Project Initialization

(this involves bounty-workers)

- [x] abebeos/PowerPC#17 Initial Project-Setup and Analysis
- [x] https://github.com/abebeos/runtimelab-ppc/issues/3 - Subsystems & Effort Assessment
- [ ] https://github.com/abebeos/runtimelab-ppc/issues/2 - Attempt to Achieve 100% Error-Free Build
- [ ] Setup Test-System, start fixing test-failures
- [ ] Fix tests, estimate amount of work for different subsystems

## Stage 2: Broader Development

(this involves bounty-workers and contributors) 

- [ ] Process all Subsystems/Packages
    * Document relevant tasks on relevant subsystems
    *  initialize work on subsystem
    * repeat until all subsystems are in-development

## Stage 3: Official Project Initialization

(this involves bounty-workers, contributors andMS/IBM-experts)

- [ ] Move `feature/ppc64le` branch over to https://github.com/dotnet/runtimelab
- [ ] Test-Stabilize-Refine cycles

## Stage 4: Main Merge

- [ ] Merge to main https://github.com/dotnet/runtime
- [ ] Post Merge Maintenance (e.g. a month)
